---
title: 'HW 01: Gapminder Exploration'
author: "Kaitlin Sullivan"
output: github_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Gapminder Dataframe

### *Let's explore the gapminder dataframe!*

```{r, echo = FALSE}
library(gapminder)
library(tibble)
```

The gapminder dataframe contains __6 columns__ with information about __life expectancies, population,__ and __GDP percapita__ in various countries.

```{r}
#number of columns in the gapminder dataframe
ncol(gapminder)

#names of columns in the gapminder dataframe
names(gapminder)
```

 There is information provided __every 5 years__, from __1952-2007__.
 
```{r}
#interval of years between datapoints
interval<-(gapminder$year[2]-gapminder$year[1])
paste(c('data provided every', interval, 'years'), collapse = " ")

#minimum and maximum year in gapminder dataset
x<-min(gapminder$year)
y<-max(gapminder$year)
paste(c('from', x,'to', y), collapse = " ")
```

 
 The average life expectancy at birth in __1952__ was __49 years__.
 
```{r}
#average life expectancy 1952
minExp<-subset(gapminder, year == 1952, lifeExp)
mean(minExp$lifeExp)
```

The average life expectancy at birth in __2007__ was __67 years__.

```{r}
#average life expectancy 2007
maxExp<-subset(gapminder, year == 2007, lifeExp)
mean(maxExp$lifeExp)
```
 
